"""Engine REST surface.

FastAPI router exposing engine primitives over HTTP. Routes are extracted
from ``src/dataraum/mcp/server.py`` handlers route-by-route — engine logic
moves to ``services.py``; presentation/shaping stays in the route handler;
the MCP-protocol envelope (tool descriptions, agent hints) is dropped.

The router is mounted onto the FastAPI control plane at ``/api`` by
``src/dataraum/server/app.py``. Spec at ``/openapi.json`` is generated by
FastAPI from the Pydantic response models on each route.
"""

from dataraum.api.routes import api_router

__all__ = ["api_router"]
