"""Entropy Interpretation Database Models.

SQLAlchemy model for LLM-generated entropy interpretations:
- EntropyInterpretationRecord: Assumptions, resolution actions, explanations

Split from db_models.py to give the entropy_interpretation phase its own db_models module.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any
from uuid import uuid4

# Use JSONB for PostgreSQL, JSON for SQLite (JSON handles serialization automatically)
from sqlalchemy import JSON, DateTime, ForeignKey, Index, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from dataraum.storage import Base

JSON_TYPE = JSONB().with_variant(JSON, "sqlite")


class EntropyInterpretationRecord(Base):
    """Persisted LLM interpretation of entropy metrics.

    Contains assumptions, resolution actions, and explanations
    generated by LLM for a column's entropy profile.
    """

    __tablename__ = "entropy_interpretations"

    interpretation_id: Mapped[str] = mapped_column(
        String, primary_key=True, default=lambda: str(uuid4())
    )

    # What was interpreted
    source_id: Mapped[str | None] = mapped_column(ForeignKey("sources.source_id"))
    table_id: Mapped[str | None] = mapped_column(ForeignKey("tables.table_id"))
    column_id: Mapped[str | None] = mapped_column(ForeignKey("columns.column_id"))
    table_name: Mapped[str] = mapped_column(String, nullable=False)
    column_name: Mapped[str | None] = mapped_column(String, nullable=True)

    # LLM-generated content
    explanation: Mapped[str] = mapped_column(String, nullable=False)

    # Assumptions as JSON list
    # Each: {"dimension": str, "assumption_text": str, "confidence": str, "impact": str, "basis": str}
    assumptions_json: Mapped[list[dict[str, Any]] | None] = mapped_column(JSON_TYPE)

    # Resolution actions as JSON list
    # Each: {"action": str, "description": str, "effort": str, "expected_impact": str, "parameters": dict}
    resolution_actions_json: Mapped[list[dict[str, Any]] | None] = mapped_column(JSON_TYPE)

    # Metadata
    model_used: Mapped[str | None] = mapped_column(String)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=lambda: datetime.now(UTC)
    )


Index("idx_interpretation_table", EntropyInterpretationRecord.table_id)
Index("idx_interpretation_column", EntropyInterpretationRecord.column_id)
