"""Entropy Interpretation Agent - LLM-powered entropy analysis.

This agent interprets entropy metrics to generate contextual assumptions,
resolution actions, and explanations. It replaces hardcoded heuristics
with LLM-powered semantic interpretation.

See BACKLOG.md Step 2.5.3 for context.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, Field, field_validator
from sqlalchemy.orm import Session

from dataraum.core.logging import get_logger
from dataraum.core.models.base import Result

logger = get_logger(__name__)

if TYPE_CHECKING:
    from dataraum.llm.config import LLMConfig
    from dataraum.llm.prompts import PromptRenderer
    from dataraum.llm.providers.base import LLMProvider


@dataclass
class Assumption:
    """An assumption about uncertain data.

    Generated by LLM based on entropy metrics and column context.
    """

    dimension: str  # e.g., "semantic.units", "value.nulls"
    assumption_text: str  # Human-readable assumption
    confidence: str  # "high", "medium", "low"
    impact: str  # What could go wrong if assumption is incorrect
    basis: str = "inferred"  # "inferred", "default", "user_specified"


@dataclass
class ResolutionAction:
    """A suggested action to reduce entropy.

    Generated by LLM with contextual descriptions.
    """

    action: str  # e.g., "document_unit", "document_null_semantics"
    description: str  # Human-readable description
    effort: str  # "low", "medium", "high"
    expected_impact: str  # What dimensions this will improve
    parameters: dict[str, Any] = field(default_factory=dict)


@dataclass
class EntropyInterpretation:
    """Complete interpretation of a column's entropy profile.

    Contains LLM-generated assumptions, resolution actions, and explanation.
    """

    column_name: str | None  # None for table-level interpretations
    table_name: str

    # LLM-generated content
    assumptions: list[Assumption]
    resolution_actions: list[ResolutionAction]
    explanation: str  # Human-readable summary

    # Metadata
    model_used: str | None = None

    def to_dashboard_dict(self) -> dict[str, Any]:
        """Convert interpretation to dashboard-friendly dictionary.

        Returns a clean structure suitable for JSON serialization and UI display.
        """
        return {
            "column_key": f"{self.table_name}.{self.column_name}"
            if self.column_name
            else self.table_name,
            "table_name": self.table_name,
            "column_name": self.column_name,
            "explanation": self.explanation,
            "assumptions": [
                {
                    "dimension": a.dimension,
                    "text": a.assumption_text,
                    "confidence": a.confidence,
                    "impact": a.impact,
                }
                for a in self.assumptions
            ],
            "resolution_actions": [
                {
                    "action": r.action,
                    "description": r.description,
                    "effort": r.effort,
                    "parameters": r.parameters,
                }
                for r in self.resolution_actions
            ],
            "metadata": {
                "model_used": self.model_used,
            },
        }


@dataclass
class InterpretationInput:
    """Input data for entropy interpretation.

    Contains the minimal context needed for LLM interpretation:
    column identity, type, quality context, and Bayesian network analysis.

    The network_analysis dict provides pre-computed causal analysis:
    intent readiness, high-impact nodes, and top fix.
    """

    table_name: str
    column_name: str
    detected_type: str
    business_description: str | None

    # Quality context from ColumnQualityReport (optional, added in interpretation phase)
    quality_grade: str | None = None
    quality_findings: list[str] | None = None

    # Network analysis from Bayesian network (added in interpretation phase)
    network_analysis: dict[str, Any] | None = None


@dataclass
class TableInterpretationInput:
    """Input data for table-level entropy interpretation.

    Contains table identity, column count, network-derived analysis,
    and enrichment context (dimensional patterns, column interpretation
    summaries, quality overview).

    The network_analysis dict provides per-table Bayesian network
    aggregation: intent readiness, column readiness counts, top fix,
    and per-column compact summaries.
    """

    table_name: str
    column_count: int

    # Network analysis from Bayesian network (added in interpretation phase)
    network_analysis: dict[str, Any] | None = None

    # Enrichment context (set by interpretation phase)
    dimensional_patterns: list[dict[str, Any]] | None = None
    column_interpretations_summary: list[dict[str, Any]] | None = None
    quality_overview: dict[str, Any] | None = None


# =============================================================================
# Pydantic models for LLM tool output
# =============================================================================


class AssumptionOutput(BaseModel):
    """Pydantic model for assumption in LLM tool output."""

    dimension: str = Field(
        description="Entropy dimension this assumption addresses, e.g., 'semantic.units', 'value.nulls'"
    )
    assumption_text: str = Field(description="Human-readable assumption statement")
    confidence: Literal["high", "medium", "low"] = Field(
        description="Confidence level in this assumption"
    )
    impact: str = Field(description="What could go wrong if this assumption is incorrect")


# Valid action prefixes for resolution actions
VALID_ACTION_PREFIXES = ("document_", "investigate_", "transform_", "create_")


class ResolutionActionOutput(BaseModel):
    """Pydantic model for resolution action in LLM tool output."""

    action: str = Field(
        description="Action identifier. Must start with: document_, investigate_, transform_, or create_"
    )
    description: str = Field(description="Human-readable description of the action")
    effort: Literal["low", "medium", "high"] = Field(description="Effort required to implement")
    expected_impact: str = Field(description="What entropy dimensions this will improve")
    parameters: dict[str, str] = Field(
        default_factory=dict,
        description="Actionable parameters (e.g., column_name, threshold, strategy, target_table)",
    )

    @field_validator("action")
    @classmethod
    def validate_action_prefix(cls, v: str) -> str:
        """Validate and normalize action prefix.

        If the action doesn't start with a valid prefix, automatically
        add 'document_' as the default prefix rather than rejecting.
        This allows LLM to generate contextual actions like 'account_structure'
        which becomes 'document_account_structure'.
        """
        if not v.startswith(VALID_ACTION_PREFIXES):
            return f"document_{v}"
        return v


class ColumnInterpretationOutput(BaseModel):
    """Pydantic model for a single column interpretation in LLM tool output."""

    assumptions: list[AssumptionOutput] = Field(
        default_factory=list, description="List of assumptions about this column's data"
    )
    resolution_actions: list[ResolutionActionOutput] = Field(
        default_factory=list, description="List of suggested actions to reduce uncertainty"
    )
    explanation: str = Field(
        description="Brief human-readable explanation of the data quality situation"
    )


class EntropyInterpretationOutput(BaseModel):
    """Pydantic model for LLM tool output - batch entropy interpretation.

    Used as a tool definition for structured LLM output via tool use API.
    """

    columns: dict[str, ColumnInterpretationOutput] = Field(
        description="Interpretations keyed by 'table_name.column_name'"
    )


class TableInterpretationLLMOutput(BaseModel):
    """Pydantic model for a single table interpretation in LLM tool output."""

    assumptions: list[AssumptionOutput] = Field(
        default_factory=list, description="List of table-wide assumptions"
    )
    resolution_actions: list[ResolutionActionOutput] = Field(
        default_factory=list, description="List of table-wide actions to reduce uncertainty"
    )
    explanation: str = Field(description="Brief explanation of the table's overall data quality")


class TableEntropyInterpretationOutput(BaseModel):
    """Pydantic model for LLM tool output - batch table interpretation."""

    tables: dict[str, TableInterpretationLLMOutput] = Field(
        description="Interpretations keyed by table_name"
    )


class EntropyInterpreter:
    """LLM-powered entropy interpreter.

    Analyzes entropy metrics and generates contextual assumptions,
    resolution actions, and explanations using structured tool output.

    Note: This class follows the LLMFeature pattern but doesn't inherit
    from it directly to avoid circular imports with entropy module.
    """

    def __init__(
        self,
        config: LLMConfig,
        provider: LLMProvider,
        prompt_renderer: PromptRenderer,
    ) -> None:
        """Initialize entropy interpreter.

        Args:
            config: LLM configuration
            provider: LLM provider instance
            prompt_renderer: Prompt template renderer
        """
        self.config = config
        self.provider = provider
        self.renderer = prompt_renderer

    def interpret_batch(
        self,
        session: Session,
        inputs: list[InterpretationInput],
    ) -> Result[dict[str, EntropyInterpretation]]:
        """Interpret entropy for multiple columns in a single LLM call.

        Makes a single batch LLM call for all columns using tool-based output.

        Args:
            session: Database session
            inputs: List of InterpretationInput for each column

        Returns:
            Result containing dict mapping column keys to interpretations
        """
        from dataraum.llm.providers.base import (
            ConversationRequest,
            Message,
            ToolDefinition,
        )

        if not inputs:
            return Result.fail("No inputs provided for interpretation")

        feature_config = self.config.features.entropy_interpretation
        if not feature_config or not feature_config.enabled:
            return Result.fail("entropy_interpretation is disabled in config")

        prompt_name = "entropy_interpretation"

        # Build columns JSON for prompt — compact form with network analysis
        columns_data = []
        for inp in inputs:
            if inp.network_analysis is None:
                logger.error(
                    "interpretation_missing_network_analysis",
                    column=f"{inp.table_name}.{inp.column_name}",
                    message="Column has no network_analysis — skipping from interpretation batch",
                )
                continue

            col_entry: dict[str, Any] = {
                "key": f"{inp.table_name}.{inp.column_name}",
                "table_name": inp.table_name,
                "column_name": inp.column_name,
                "detected_type": inp.detected_type,
                "business_description": inp.business_description or "Not documented",
                "network_analysis": inp.network_analysis,
            }
            # Add quality context if available
            if inp.quality_grade:
                col_entry["quality_grade"] = inp.quality_grade
            if inp.quality_findings:
                col_entry["quality_findings"] = inp.quality_findings
            columns_data.append(col_entry)

        context: dict[str, str] = {
            "columns_json": json.dumps(columns_data, indent=2),
        }

        # Render prompt with system/user split
        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                prompt_name, context
            )
        except Exception as e:
            return Result.fail(f"Failed to render prompt: {e}")

        # Define tool for structured output
        tool = ToolDefinition(
            name="interpret_entropy",
            description="Provide structured interpretation of entropy metrics for the columns",
            input_schema=EntropyInterpretationOutput.model_json_schema(),
        )

        model = self.provider.get_model_for_tier(feature_config.model_tier)

        # Call LLM with tool use
        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "interpret_entropy"},
            max_tokens=self.config.limits.max_output_tokens_per_request,
            temperature=temperature,
        )

        # Retry logic for transient failures
        max_retries = 2
        last_error = None

        for _attempt in range(max_retries + 1):
            result = self.provider.converse(request)
            if not result.success or not result.value:
                last_error = result.error or "LLM call failed"
                continue

            response = result.value

            # Extract tool call result
            if not response.tool_calls:
                last_error = f"LLM did not use the interpret_entropy tool. Response: {(response.content or '')[:200]}"
                continue

            # Parse tool response using Pydantic model
            tool_call = response.tool_calls[0]
            if tool_call.name != "interpret_entropy":
                last_error = f"Unexpected tool call: {tool_call.name}"
                continue

            try:
                output = EntropyInterpretationOutput.model_validate(tool_call.input)
                # Diagnostic: log raw tool input when output is empty or partial
                if len(output.columns) < len(inputs):
                    raw_keys = (
                        list(tool_call.input.get("columns", {}).keys())
                        if isinstance(tool_call.input, dict)
                        else []
                    )
                    expected_keys = [f"{inp.table_name}.{inp.column_name}" for inp in inputs]
                    logger.warning(
                        "interpretation_raw_response_diagnostic",
                        parsed_column_count=len(output.columns),
                        expected_column_count=len(inputs),
                        raw_tool_keys=raw_keys[:20],
                        expected_keys=expected_keys[:20],
                        raw_top_level_keys=list(tool_call.input.keys())
                        if isinstance(tool_call.input, dict)
                        else str(type(tool_call.input)),
                    )
                return self._convert_output_to_interpretations(inputs, output, model)
            except Exception as e:
                last_error = f"Failed to validate tool response: {e}"
                continue

        # All retries failed
        return Result.fail(last_error or "All retry attempts failed")

    def _convert_output_to_interpretations(
        self,
        inputs: list[InterpretationInput],
        output: EntropyInterpretationOutput,
        model: str,
    ) -> Result[dict[str, EntropyInterpretation]]:
        """Convert Pydantic tool output to EntropyInterpretation dataclasses.

        Args:
            inputs: Original input data for each column
            output: Validated Pydantic output from LLM
            model: Model name used for generation

        Returns:
            Result containing dict mapping column keys to interpretations
        """
        # Build lookup for inputs
        inputs_by_key = {f"{inp.table_name}.{inp.column_name}": inp for inp in inputs}

        interpretations: dict[str, EntropyInterpretation] = {}

        # Track key mismatches for diagnostics
        expected_keys = set(inputs_by_key.keys())
        returned_keys = set(output.columns.keys())
        matched_keys = expected_keys & returned_keys
        unmatched_returned = returned_keys - expected_keys
        missing_keys = expected_keys - returned_keys

        if unmatched_returned:
            # Dump side-by-side comparison so we can diagnose the root cause
            # (casing, prefix, hallucination, whitespace, etc.)
            pairs: list[dict[str, str]] = []
            remaining_expected = sorted(missing_keys)
            for ret_key in sorted(unmatched_returned):
                # Try to find the closest expected key for diagnosis
                best_match = None
                ret_lower = ret_key.lower().strip()
                for exp_key in remaining_expected:
                    if exp_key.lower().strip() == ret_lower:
                        best_match = exp_key
                        break
                pairs.append(
                    {
                        "returned": repr(ret_key),
                        "closest_expected": repr(best_match)
                        if best_match
                        else "<no case-insensitive match>",
                    }
                )
                if best_match:
                    remaining_expected.remove(best_match)
            logger.warning(
                "interpretation_key_mismatch",
                matched=len(matched_keys),
                expected=len(expected_keys),
                returned=len(returned_keys),
                unmatched_returned_keys=sorted(unmatched_returned),
                missing_expected_keys=sorted(missing_keys),
                diagnostic_pairs=pairs,
            )

        if len(matched_keys) < len(expected_keys):
            logger.warning(
                "interpretation_columns_lost",
                matched=len(matched_keys),
                total_expected=len(expected_keys),
                total_returned=len(returned_keys),
            )

        for key, col_output in output.columns.items():
            inp = inputs_by_key.get(key)
            if not inp:
                continue

            # Convert assumptions
            assumptions = [
                Assumption(
                    dimension=a.dimension,
                    assumption_text=a.assumption_text,
                    confidence=a.confidence,
                    impact=a.impact,
                    basis="inferred",
                )
                for a in col_output.assumptions
            ]

            # Convert resolution actions
            resolution_actions = [
                ResolutionAction(
                    action=r.action,
                    description=r.description,
                    effort=r.effort,
                    expected_impact=r.expected_impact,
                    parameters=r.parameters,
                )
                for r in col_output.resolution_actions
            ]

            interpretations[key] = EntropyInterpretation(
                column_name=inp.column_name,
                table_name=inp.table_name,
                assumptions=assumptions,
                resolution_actions=resolution_actions,
                explanation=col_output.explanation,
                model_used=model,
            )

        return Result.ok(interpretations)

    def interpret_tables(
        self,
        session: Session,
        inputs: list[TableInterpretationInput],
    ) -> Result[dict[str, EntropyInterpretation]]:
        """Interpret entropy at the table level.

        Makes a single batch LLM call for all tables using tool-based output.

        Args:
            session: Database session
            inputs: List of TableInterpretationInput for each table

        Returns:
            Result containing dict mapping table_name to interpretations
        """
        from dataraum.llm.providers.base import (
            ConversationRequest,
            Message,
            ToolDefinition,
        )

        if not inputs:
            return Result.fail("No inputs provided for table interpretation")

        feature_config = self.config.features.entropy_interpretation
        if not feature_config or not feature_config.enabled:
            return Result.fail("entropy_interpretation is disabled in config")

        # Build tables JSON for prompt — compact form with network analysis
        tables_data = []
        for inp in inputs:
            if inp.network_analysis is None:
                logger.error(
                    "table_interpretation_missing_network_analysis",
                    table=inp.table_name,
                    message="Table has no network_analysis — skipping from interpretation batch",
                )
                continue

            table_entry: dict[str, Any] = {
                "table_name": inp.table_name,
                "column_count": inp.column_count,
                "network_analysis": inp.network_analysis,
            }
            # Add enrichment context if available
            if inp.dimensional_patterns:
                table_entry["dimensional_patterns"] = inp.dimensional_patterns
            if inp.column_interpretations_summary:
                table_entry["column_interpretations_summary"] = inp.column_interpretations_summary
            if inp.quality_overview:
                table_entry["quality_overview"] = inp.quality_overview
            tables_data.append(table_entry)

        # Extract resolution guidelines from column prompt for reuse
        resolution_guidelines = ""
        try:
            _, full_system, _ = self.renderer.render_split(
                "entropy_interpretation", {"columns_json": "[]"}
            )
            # Extract resolution_guidelines section if present
            if "<resolution_guidelines>" in full_system:
                start = full_system.index("<resolution_guidelines>")
                end = full_system.index("</resolution_guidelines>") + len(
                    "</resolution_guidelines>"
                )
                resolution_guidelines = full_system[start:end]
        except Exception:
            pass

        context: dict[str, str] = {
            "tables_json": json.dumps(tables_data, indent=2),
            "resolution_guidelines": resolution_guidelines,
        }

        # Render prompt
        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                "entropy_table_interpretation", context
            )
        except Exception as e:
            return Result.fail(f"Failed to render table interpretation prompt: {e}")

        # Define tool for structured output
        tool = ToolDefinition(
            name="interpret_table_entropy",
            description="Provide structured interpretation of entropy metrics for the tables",
            input_schema=TableEntropyInterpretationOutput.model_json_schema(),
        )

        model = self.provider.get_model_for_tier(feature_config.model_tier)

        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "interpret_table_entropy"},
            max_tokens=self.config.limits.max_output_tokens_per_request,
            temperature=temperature,
        )

        # Retry logic
        max_retries = 2
        last_error = None

        for _attempt in range(max_retries + 1):
            result = self.provider.converse(request)
            if not result.success or not result.value:
                last_error = result.error or "LLM call failed"
                continue

            response = result.value

            if not response.tool_calls:
                last_error = f"LLM did not use the interpret_table_entropy tool. Response: {(response.content or '')[:200]}"
                continue

            tool_call = response.tool_calls[0]
            if tool_call.name != "interpret_table_entropy":
                last_error = f"Unexpected tool call: {tool_call.name}"
                continue

            try:
                output = TableEntropyInterpretationOutput.model_validate(tool_call.input)
                # Diagnostic: log raw tool input when output is empty or partial
                if len(output.tables) < len(inputs):
                    raw_keys = (
                        list(tool_call.input.get("tables", {}).keys())
                        if isinstance(tool_call.input, dict)
                        else []
                    )
                    expected_keys = [inp.table_name for inp in inputs]
                    logger.warning(
                        "table_interpretation_raw_response_diagnostic",
                        parsed_table_count=len(output.tables),
                        expected_table_count=len(inputs),
                        raw_tool_keys=raw_keys[:20],
                        expected_keys=expected_keys[:20],
                        raw_top_level_keys=list(tool_call.input.keys())
                        if isinstance(tool_call.input, dict)
                        else str(type(tool_call.input)),
                    )
                return self._convert_table_output(inputs, output, model)
            except Exception as e:
                last_error = f"Failed to validate tool response: {e}"
                continue

        return Result.fail(last_error or "All retry attempts failed")

    def _convert_table_output(
        self,
        inputs: list[TableInterpretationInput],
        output: TableEntropyInterpretationOutput,
        model: str,
    ) -> Result[dict[str, EntropyInterpretation]]:
        """Convert table LLM output to EntropyInterpretation dataclasses."""
        inputs_by_name = {inp.table_name: inp for inp in inputs}
        interpretations: dict[str, EntropyInterpretation] = {}

        # Track key mismatches
        expected_keys = set(inputs_by_name.keys())
        returned_keys = set(output.tables.keys())
        unmatched = returned_keys - expected_keys
        missing = expected_keys - returned_keys
        if unmatched:
            pairs: list[dict[str, str]] = []
            remaining_expected = sorted(missing)
            for ret_key in sorted(unmatched):
                best_match = None
                ret_lower = ret_key.lower().strip()
                for exp_key in remaining_expected:
                    if exp_key.lower().strip() == ret_lower:
                        best_match = exp_key
                        break
                pairs.append(
                    {
                        "returned": repr(ret_key),
                        "closest_expected": repr(best_match)
                        if best_match
                        else "<no case-insensitive match>",
                    }
                )
                if best_match:
                    remaining_expected.remove(best_match)
            logger.warning(
                "table_interpretation_key_mismatch",
                expected_keys=sorted(expected_keys),
                returned_keys=sorted(returned_keys),
                unmatched=sorted(unmatched),
                diagnostic_pairs=pairs,
            )

        for table_name, table_output in output.tables.items():
            inp = inputs_by_name.get(table_name)
            if not inp:
                continue

            assumptions = [
                Assumption(
                    dimension=a.dimension,
                    assumption_text=a.assumption_text,
                    confidence=a.confidence,
                    impact=a.impact,
                    basis="inferred",
                )
                for a in table_output.assumptions
            ]

            resolution_actions = [
                ResolutionAction(
                    action=r.action,
                    description=r.description,
                    effort=r.effort,
                    expected_impact=r.expected_impact,
                    parameters=r.parameters,
                )
                for r in table_output.resolution_actions
            ]

            interpretations[table_name] = EntropyInterpretation(
                column_name=None,
                table_name=table_name,
                assumptions=assumptions,
                resolution_actions=resolution_actions,
                explanation=table_output.explanation,
                model_used=model,
            )

        return Result.ok(interpretations)


__all__ = [
    "Assumption",
    "ResolutionAction",
    "EntropyInterpretation",
    "InterpretationInput",
    "TableInterpretationInput",
    "EntropyInterpreter",
    # Pydantic output models for tool use
    "AssumptionOutput",
    "ResolutionActionOutput",
    "ColumnInterpretationOutput",
    "EntropyInterpretationOutput",
    "TableInterpretationLLMOutput",
    "TableEntropyInterpretationOutput",
]
