"""Entropy Interpretation Agent - LLM-powered entropy analysis.

This agent interprets entropy metrics to generate contextual assumptions,
resolution actions, and explanations. It replaces hardcoded heuristics
with LLM-powered semantic interpretation.

See BACKLOG.md Step 2.5.3 for context.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, Field, field_validator
from sqlalchemy.orm import Session

from dataraum.core.logging import get_logger
from dataraum.core.models.base import Result

logger = get_logger(__name__)

if TYPE_CHECKING:
    from dataraum.llm.config import LLMConfig
    from dataraum.llm.prompts import PromptRenderer
    from dataraum.llm.providers.base import LLMProvider


@dataclass
class Assumption:
    """An assumption about uncertain data.

    Generated by LLM based on entropy metrics and column context.
    """

    dimension: str  # e.g., "semantic.units", "value.nulls"
    assumption_text: str  # Human-readable assumption
    confidence: str  # "high", "medium", "low"
    impact: str  # What could go wrong if assumption is incorrect
    basis: str = "inferred"  # "inferred", "default", "user_specified"


@dataclass
class ResolutionAction:
    """A suggested action to reduce entropy.

    Generated by LLM with contextual descriptions.
    """

    action: str  # e.g., "document_unit", "document_null_semantics"
    description: str  # Human-readable description
    effort: str  # "low", "medium", "high"
    expected_impact: str  # What dimensions this will improve
    parameters: dict[str, Any] = field(default_factory=dict)


@dataclass
class EntropyInterpretation:
    """Complete interpretation of a column's entropy profile.

    Contains LLM-generated assumptions, resolution actions, and explanation.
    """

    column_name: str | None  # None for table-level interpretations
    table_name: str

    # LLM-generated content
    assumptions: list[Assumption]
    resolution_actions: list[ResolutionAction]
    explanation: str  # Human-readable summary

    # Metadata
    model_used: str | None = None

    def to_dashboard_dict(self) -> dict[str, Any]:
        """Convert interpretation to dashboard-friendly dictionary.

        Returns a clean structure suitable for JSON serialization and UI display.
        """
        return {
            "column_key": f"{self.table_name}.{self.column_name}"
            if self.column_name
            else self.table_name,
            "table_name": self.table_name,
            "column_name": self.column_name,
            "explanation": self.explanation,
            "assumptions": [
                {
                    "dimension": a.dimension,
                    "text": a.assumption_text,
                    "confidence": a.confidence,
                    "impact": a.impact,
                }
                for a in self.assumptions
            ],
            "resolution_actions": [
                {
                    "action": r.action,
                    "description": r.description,
                    "effort": r.effort,
                    "parameters": r.parameters,
                }
                for r in self.resolution_actions
            ],
            "metadata": {
                "model_used": self.model_used,
            },
        }


@dataclass
class InterpretationInput:
    """Input data for entropy interpretation.

    Contains the minimal context needed for LLM interpretation:
    column identity, type, quality context, and Bayesian network analysis.

    The network_analysis dict provides pre-computed causal analysis:
    intent readiness, high-impact nodes, and top fix.
    """

    table_name: str
    column_name: str
    detected_type: str
    business_description: str | None

    # Quality context from ColumnQualityReport (optional, added in interpretation phase)
    quality_grade: str | None = None
    quality_findings: list[str] | None = None

    # Network analysis from Bayesian network (added in interpretation phase)
    network_analysis: dict[str, Any] | None = None


@dataclass
class TableInterpretationInput:
    """Input data for table-level entropy interpretation.

    Contains table identity, column count, network-derived analysis,
    and enrichment context (dimensional patterns, column interpretation
    summaries, quality overview).

    The network_analysis dict provides per-table Bayesian network
    aggregation: intent readiness, column readiness counts, top fix,
    and per-column compact summaries.
    """

    table_name: str
    column_count: int

    # Network analysis from Bayesian network (added in interpretation phase)
    network_analysis: dict[str, Any] | None = None

    # Enrichment context (set by interpretation phase)
    dimensional_patterns: list[dict[str, Any]] | None = None
    column_interpretations_summary: list[dict[str, Any]] | None = None
    quality_overview: dict[str, Any] | None = None


# =============================================================================
# Pydantic models for LLM tool output
# =============================================================================


class AssumptionOutput(BaseModel):
    """Pydantic model for assumption in LLM tool output."""

    dimension: str = Field(
        description="Entropy dimension this assumption addresses, e.g., 'semantic.units', 'value.nulls'"
    )
    assumption_text: str = Field(description="Human-readable assumption statement")
    confidence: Literal["high", "medium", "low"] = Field(
        description="Confidence level in this assumption"
    )
    impact: str = Field(description="What could go wrong if this assumption is incorrect")


# Valid action prefixes for resolution actions
VALID_ACTION_PREFIXES = ("document_", "investigate_", "transform_", "create_")


class ResolutionActionOutput(BaseModel):
    """Pydantic model for resolution action in LLM tool output."""

    action: str = Field(
        description="Action identifier. Must start with: document_, investigate_, transform_, or create_"
    )
    description: str = Field(description="Human-readable description of the action")
    effort: Literal["low", "medium", "high"] = Field(description="Effort required to implement")
    expected_impact: str = Field(description="What entropy dimensions this will improve")
    parameters: dict[str, str] = Field(
        default_factory=dict,
        description="Actionable parameters (e.g., column_name, threshold, strategy, target_table)",
    )

    @field_validator("action")
    @classmethod
    def validate_action_prefix(cls, v: str) -> str:
        """Validate and normalize action prefix.

        If the action doesn't start with a valid prefix, automatically
        add 'document_' as the default prefix rather than rejecting.
        This allows LLM to generate contextual actions like 'account_structure'
        which becomes 'document_account_structure'.
        """
        if not v.startswith(VALID_ACTION_PREFIXES):
            return f"document_{v}"
        return v


# --- Tier 1: Structured output (no explanation) ---


class Tier1ColumnOutput(BaseModel):
    """Tier 1 (Haiku) output for a single column: assumptions + actions only."""

    assumptions: list[AssumptionOutput] = Field(default_factory=list)
    resolution_actions: list[ResolutionActionOutput] = Field(default_factory=list)


class Tier1InterpretationOutput(BaseModel):
    """Tier 1 batch output for columns."""

    columns: dict[str, Tier1ColumnOutput] = Field(
        description="Interpretations keyed by 'table_name.column_name'"
    )


class Tier1TableOutput(BaseModel):
    """Tier 1 (Haiku) output for a single table: assumptions + actions only."""

    assumptions: list[AssumptionOutput] = Field(default_factory=list)
    resolution_actions: list[ResolutionActionOutput] = Field(default_factory=list)


class Tier1TableInterpretationOutput(BaseModel):
    """Tier 1 batch output for tables."""

    tables: dict[str, Tier1TableOutput] = Field(
        description="Interpretations keyed by table_name"
    )


# --- Tier 2: Explanation synthesis only ---


class Tier2ExplanationOutput(BaseModel):
    """Tier 2 (Sonnet) output for a single item: explanation only."""

    explanation: str = Field(description="Concise data quality explanation")


class Tier2InterpretationsOutput(BaseModel):
    """Tier 2 batch output: explanations for all columns and tables."""

    items: dict[str, Tier2ExplanationOutput] = Field(
        description="Explanations keyed by 'table_name.column_name' or table_name"
    )


class EntropyInterpreter:
    """LLM-powered entropy interpreter.

    Analyzes entropy metrics and generates contextual assumptions,
    resolution actions, and explanations using structured tool output.

    Note: This class follows the LLMFeature pattern but doesn't inherit
    from it directly to avoid circular imports with entropy module.
    """

    def __init__(
        self,
        config: LLMConfig,
        provider: LLMProvider,
        prompt_renderer: PromptRenderer,
    ) -> None:
        """Initialize entropy interpreter.

        Args:
            config: LLM configuration
            provider: LLM provider instance
            prompt_renderer: Prompt template renderer
        """
        self.config = config
        self.provider = provider
        self.renderer = prompt_renderer

    # =========================================================================
    # Tier 1: Structured extraction (Haiku) — assumptions + actions only
    # =========================================================================

    def interpret_batch_tier1(
        self,
        session: Session,
        inputs: list[InterpretationInput],
    ) -> Result[dict[str, Tier1ColumnOutput]]:
        """Tier 1: Extract assumptions and actions for columns (no explanation).

        Uses fast model (Haiku) for structured extraction.

        Args:
            session: Database session
            inputs: List of InterpretationInput for each column

        Returns:
            Result containing dict mapping column keys to Tier1ColumnOutput
        """
        from dataraum.llm.providers.base import (
            ConversationRequest,
            Message,
            ToolDefinition,
        )

        if not inputs:
            return Result.fail("No inputs provided for interpretation")

        feature_config = self.config.features.entropy_interpretation_structured
        if not feature_config or not feature_config.enabled:
            return Result.fail("entropy_interpretation_structured is disabled in config")

        # Build columns JSON for prompt — compact form with network analysis
        columns_data = []
        for inp in inputs:
            if inp.network_analysis is None:
                logger.error(
                    "interpretation_missing_network_analysis",
                    column=f"{inp.table_name}.{inp.column_name}",
                    message="Column has no network_analysis — skipping from T1 batch",
                )
                continue

            col_entry: dict[str, Any] = {
                "key": f"{inp.table_name}.{inp.column_name}",
                "table_name": inp.table_name,
                "column_name": inp.column_name,
                "detected_type": inp.detected_type,
                "business_description": inp.business_description or "Not documented",
                "network_analysis": inp.network_analysis,
            }
            if inp.quality_grade:
                col_entry["quality_grade"] = inp.quality_grade
            if inp.quality_findings:
                col_entry["quality_findings"] = inp.quality_findings
            columns_data.append(col_entry)

        context: dict[str, str] = {
            "columns_json": json.dumps(columns_data, indent=2),
        }

        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                "entropy_tier1", context
            )
        except Exception as e:
            return Result.fail(f"Failed to render T1 prompt: {e}")

        tool = ToolDefinition(
            name="interpret_entropy_structured",
            description="Provide structured assumptions and actions for the columns",
            input_schema=Tier1InterpretationOutput.model_json_schema(),
        )

        model = self.provider.get_model_for_tier(feature_config.model_tier)

        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "interpret_entropy_structured"},
            max_tokens=self.config.limits.max_output_tokens_per_request,
            temperature=temperature,
        )

        max_retries = 2
        last_error = None

        for _attempt in range(max_retries + 1):
            result = self.provider.converse(request)
            if not result.success or not result.value:
                last_error = result.error or "LLM call failed"
                continue

            response = result.value

            if not response.tool_calls:
                last_error = f"LLM did not use the interpret_entropy_structured tool. Response: {(response.content or '')[:200]}"
                continue

            tool_call = response.tool_calls[0]
            if tool_call.name != "interpret_entropy_structured":
                last_error = f"Unexpected tool call: {tool_call.name}"
                continue

            try:
                output = Tier1InterpretationOutput.model_validate(tool_call.input)
                if len(output.columns) < len(inputs):
                    raw_keys = (
                        list(tool_call.input.get("columns", {}).keys())
                        if isinstance(tool_call.input, dict)
                        else []
                    )
                    expected_keys = [f"{inp.table_name}.{inp.column_name}" for inp in inputs]
                    logger.warning(
                        "tier1_column_raw_response_diagnostic",
                        parsed_column_count=len(output.columns),
                        expected_column_count=len(inputs),
                        raw_tool_keys=raw_keys[:20],
                        expected_keys=expected_keys[:20],
                    )
                # Return Tier1ColumnOutput directly — phase does the merge
                return self._match_tier1_columns(inputs, output, model)
            except Exception as e:
                last_error = f"Failed to validate T1 tool response: {e}"
                continue

        return Result.fail(last_error or "All T1 retry attempts failed")

    def _match_tier1_columns(
        self,
        inputs: list[InterpretationInput],
        output: Tier1InterpretationOutput,
        model: str,
    ) -> Result[dict[str, Tier1ColumnOutput]]:
        """Match Tier 1 column output keys to input keys.

        Returns dict of matched Tier1ColumnOutput, logging mismatches.
        """
        inputs_by_key = {f"{inp.table_name}.{inp.column_name}": inp for inp in inputs}
        expected_keys = set(inputs_by_key.keys())
        returned_keys = set(output.columns.keys())
        matched_keys = expected_keys & returned_keys
        unmatched_returned = returned_keys - expected_keys

        if unmatched_returned:
            missing_keys = expected_keys - returned_keys
            pairs: list[dict[str, str]] = []
            remaining_expected = sorted(missing_keys)
            for ret_key in sorted(unmatched_returned):
                best_match = None
                ret_lower = ret_key.lower().strip()
                for exp_key in remaining_expected:
                    if exp_key.lower().strip() == ret_lower:
                        best_match = exp_key
                        break
                pairs.append(
                    {
                        "returned": repr(ret_key),
                        "closest_expected": repr(best_match) if best_match else "<no match>",
                    }
                )
                if best_match:
                    remaining_expected.remove(best_match)
            logger.warning(
                "tier1_column_key_mismatch",
                matched=len(matched_keys),
                expected=len(expected_keys),
                returned=len(returned_keys),
                diagnostic_pairs=pairs,
            )

        if len(matched_keys) < len(expected_keys):
            logger.warning(
                "tier1_columns_lost",
                matched=len(matched_keys),
                total_expected=len(expected_keys),
            )

        results: dict[str, Tier1ColumnOutput] = {}
        for key, col_output in output.columns.items():
            if key in inputs_by_key:
                results[key] = col_output
        return Result.ok(results)

    def interpret_tables_tier1(
        self,
        session: Session,
        inputs: list[TableInterpretationInput],
    ) -> Result[dict[str, Tier1TableOutput]]:
        """Tier 1: Extract assumptions and actions for tables (no explanation).

        Uses fast model (Haiku) for structured extraction.

        Args:
            session: Database session
            inputs: List of TableInterpretationInput for each table

        Returns:
            Result containing dict mapping table_name to Tier1TableOutput
        """
        from dataraum.llm.providers.base import (
            ConversationRequest,
            Message,
            ToolDefinition,
        )

        if not inputs:
            return Result.fail("No inputs provided for table interpretation")

        feature_config = self.config.features.entropy_interpretation_structured
        if not feature_config or not feature_config.enabled:
            return Result.fail("entropy_interpretation_structured is disabled in config")

        # Build tables JSON for prompt
        tables_data = []
        for inp in inputs:
            if inp.network_analysis is None:
                logger.error(
                    "table_interpretation_missing_network_analysis",
                    table=inp.table_name,
                    message="Table has no network_analysis — skipping from T1 batch",
                )
                continue

            table_entry: dict[str, Any] = {
                "table_name": inp.table_name,
                "column_count": inp.column_count,
                "network_analysis": inp.network_analysis,
            }
            if inp.dimensional_patterns:
                table_entry["dimensional_patterns"] = inp.dimensional_patterns
            if inp.column_interpretations_summary:
                table_entry["column_interpretations_summary"] = inp.column_interpretations_summary
            if inp.quality_overview:
                table_entry["quality_overview"] = inp.quality_overview
            tables_data.append(table_entry)

        # Extract resolution guidelines from column T1 prompt for reuse
        resolution_guidelines = ""
        try:
            _, full_system, _ = self.renderer.render_split(
                "entropy_tier1", {"columns_json": "[]"}
            )
            if "<resolution_guidelines>" in full_system:
                start = full_system.index("<resolution_guidelines>")
                end = full_system.index("</resolution_guidelines>") + len(
                    "</resolution_guidelines>"
                )
                resolution_guidelines = full_system[start:end]
        except Exception:
            pass

        context: dict[str, str] = {
            "tables_json": json.dumps(tables_data, indent=2),
            "resolution_guidelines": resolution_guidelines,
        }

        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                "entropy_table_tier1", context
            )
        except Exception as e:
            return Result.fail(f"Failed to render T1 table prompt: {e}")

        tool = ToolDefinition(
            name="interpret_table_entropy_structured",
            description="Provide structured assumptions and actions for the tables",
            input_schema=Tier1TableInterpretationOutput.model_json_schema(),
        )

        model = self.provider.get_model_for_tier(feature_config.model_tier)

        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "interpret_table_entropy_structured"},
            max_tokens=self.config.limits.max_output_tokens_per_request,
            temperature=temperature,
        )

        max_retries = 2
        last_error = None

        for _attempt in range(max_retries + 1):
            result = self.provider.converse(request)
            if not result.success or not result.value:
                last_error = result.error or "LLM call failed"
                continue

            response = result.value

            if not response.tool_calls:
                last_error = f"LLM did not use the interpret_table_entropy_structured tool. Response: {(response.content or '')[:200]}"
                continue

            tool_call = response.tool_calls[0]
            if tool_call.name != "interpret_table_entropy_structured":
                last_error = f"Unexpected tool call: {tool_call.name}"
                continue

            try:
                output = Tier1TableInterpretationOutput.model_validate(tool_call.input)
                if len(output.tables) < len(inputs):
                    raw_keys = (
                        list(tool_call.input.get("tables", {}).keys())
                        if isinstance(tool_call.input, dict)
                        else []
                    )
                    expected_keys = [inp.table_name for inp in inputs]
                    logger.warning(
                        "tier1_table_raw_response_diagnostic",
                        parsed_table_count=len(output.tables),
                        expected_table_count=len(inputs),
                        raw_tool_keys=raw_keys[:20],
                        expected_keys=expected_keys[:20],
                    )
                return self._match_tier1_tables(inputs, output, model)
            except Exception as e:
                last_error = f"Failed to validate T1 table tool response: {e}"
                continue

        return Result.fail(last_error or "All T1 table retry attempts failed")

    def _match_tier1_tables(
        self,
        inputs: list[TableInterpretationInput],
        output: Tier1TableInterpretationOutput,
        model: str,
    ) -> Result[dict[str, Tier1TableOutput]]:
        """Match Tier 1 table output keys to input keys."""
        inputs_by_name = {inp.table_name: inp for inp in inputs}
        expected_keys = set(inputs_by_name.keys())
        returned_keys = set(output.tables.keys())
        unmatched = returned_keys - expected_keys

        if unmatched:
            missing = expected_keys - returned_keys
            pairs: list[dict[str, str]] = []
            remaining_expected = sorted(missing)
            for ret_key in sorted(unmatched):
                best_match = None
                ret_lower = ret_key.lower().strip()
                for exp_key in remaining_expected:
                    if exp_key.lower().strip() == ret_lower:
                        best_match = exp_key
                        break
                pairs.append(
                    {
                        "returned": repr(ret_key),
                        "closest_expected": repr(best_match) if best_match else "<no match>",
                    }
                )
                if best_match:
                    remaining_expected.remove(best_match)
            logger.warning(
                "tier1_table_key_mismatch",
                expected_keys=sorted(expected_keys),
                returned_keys=sorted(returned_keys),
                diagnostic_pairs=pairs,
            )

        results: dict[str, Tier1TableOutput] = {}
        for table_name, table_output in output.tables.items():
            if table_name in inputs_by_name:
                results[table_name] = table_output
        return Result.ok(results)

    # =========================================================================
    # Tier 2: Explanation synthesis (Sonnet) — single call for all items
    # =========================================================================

    def synthesize_explanations(
        self,
        session: Session,
        tier1_columns: dict[str, Tier1ColumnOutput],
        tier1_tables: dict[str, Tier1TableOutput],
        column_inputs: list[InterpretationInput],
        table_inputs: list[TableInterpretationInput],
    ) -> Result[dict[str, str]]:
        """Tier 2: Synthesize explanations for all columns and tables.

        Uses balanced model (Sonnet) for a single call covering all items.
        Receives compact summaries of Tier 1 output.

        Args:
            session: Database session
            tier1_columns: Tier 1 column results keyed by table.column
            tier1_tables: Tier 1 table results keyed by table_name
            column_inputs: Original column inputs (for readiness context)
            table_inputs: Original table inputs (for readiness context)

        Returns:
            Result containing dict mapping keys to explanation strings
        """
        from dataraum.llm.providers.base import (
            ConversationRequest,
            Message,
            ToolDefinition,
        )

        if not tier1_columns and not tier1_tables:
            return Result.ok({})

        feature_config = self.config.features.entropy_interpretation
        if not feature_config or not feature_config.enabled:
            return Result.fail("entropy_interpretation is disabled in config")

        # Build compact summaries for prompt — minimize input tokens
        inputs_by_key = {
            f"{inp.table_name}.{inp.column_name}": inp for inp in column_inputs
        }
        table_inputs_by_name = {inp.table_name: inp for inp in table_inputs}

        lines: list[str] = []
        for key, col_out in sorted(tier1_columns.items()):
            inp = inputs_by_key.get(key)
            readiness = "unknown"
            if inp and inp.network_analysis:
                readiness = inp.network_analysis.get("readiness", "unknown")
            assumption_parts = [
                f"{a.dimension}[{a.confidence}]" for a in col_out.assumptions
            ]
            top_action = col_out.resolution_actions[0].action if col_out.resolution_actions else None
            line = (
                f"{key}: readiness={readiness}, "
                f"{len(col_out.assumptions)} assumptions ({', '.join(assumption_parts) or 'none'}), "
                f"{len(col_out.resolution_actions)} actions"
            )
            if top_action:
                line += f" (top: {top_action})"
            lines.append(line)

        for tbl_name, tbl_out in sorted(tier1_tables.items()):
            tbl_inp = table_inputs_by_name.get(tbl_name)
            readiness = "unknown"
            if tbl_inp and tbl_inp.network_analysis:
                readiness = tbl_inp.network_analysis.get("readiness", "unknown")
            assumption_parts = [
                f"{a.dimension}[{a.confidence}]" for a in tbl_out.assumptions
            ]
            top_action = tbl_out.resolution_actions[0].action if tbl_out.resolution_actions else None
            line = (
                f"[table] {tbl_name}: readiness={readiness}, "
                f"{len(tbl_out.assumptions)} assumptions ({', '.join(assumption_parts) or 'none'}), "
                f"{len(tbl_out.resolution_actions)} actions"
            )
            if top_action:
                line += f" (top: {top_action})"
            lines.append(line)

        items_summary = "\n".join(lines)

        context: dict[str, str] = {"items_summary": items_summary}

        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                "entropy_tier2", context
            )
        except Exception as e:
            return Result.fail(f"Failed to render T2 prompt: {e}")

        tool = ToolDefinition(
            name="synthesize_explanations",
            description="Provide concise explanations for each column and table",
            input_schema=Tier2InterpretationsOutput.model_json_schema(),
        )

        # Resolve model for tier (validates tier exists)
        self.provider.get_model_for_tier(feature_config.model_tier)

        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "synthesize_explanations"},
            max_tokens=self.config.limits.max_output_tokens_per_request,
            temperature=temperature,
        )

        max_retries = 2
        last_error = None

        for _attempt in range(max_retries + 1):
            result = self.provider.converse(request)
            if not result.success or not result.value:
                last_error = result.error or "LLM call failed"
                continue

            response = result.value

            if not response.tool_calls:
                last_error = f"LLM did not use synthesize_explanations tool. Response: {(response.content or '')[:200]}"
                continue

            tool_call = response.tool_calls[0]
            if tool_call.name != "synthesize_explanations":
                last_error = f"Unexpected tool call: {tool_call.name}"
                continue

            try:
                output = Tier2InterpretationsOutput.model_validate(tool_call.input)
                # Return flat dict of key -> explanation string
                explanations: dict[str, str] = {
                    key: item.explanation for key, item in output.items.items()
                }
                return Result.ok(explanations)
            except Exception as e:
                last_error = f"Failed to validate T2 tool response: {e}"
                continue

        return Result.fail(last_error or "All T2 retry attempts failed")



__all__ = [
    "Assumption",
    "ResolutionAction",
    "EntropyInterpretation",
    "InterpretationInput",
    "TableInterpretationInput",
    "EntropyInterpreter",
    # Pydantic output models for tool use
    "AssumptionOutput",
    "ResolutionActionOutput",
    # Tier 1 (structured extraction)
    "Tier1ColumnOutput",
    "Tier1InterpretationOutput",
    "Tier1TableOutput",
    "Tier1TableInterpretationOutput",
    # Tier 2 (explanation synthesis)
    "Tier2ExplanationOutput",
    "Tier2InterpretationsOutput",
]
