"""Entropy Interpretation Agent - LLM-powered entropy analysis.

This agent interprets entropy metrics to generate contextual assumptions,
resolution actions, and explanations. It replaces hardcoded heuristics
with LLM-powered semantic interpretation.

See BACKLOG.md Step 2.5.3 for context.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, Field, field_validator
from sqlalchemy.orm import Session

from dataraum.core.logging import get_logger
from dataraum.core.models.base import Result
from dataraum.entropy.analysis.aggregator import ColumnSummary, TableSummary
from dataraum.entropy.models import CompoundRisk

logger = get_logger(__name__)

if TYPE_CHECKING:
    from dataraum.llm.config import LLMConfig
    from dataraum.llm.prompts import PromptRenderer
    from dataraum.llm.providers.base import LLMProvider


@dataclass
class Assumption:
    """An assumption about uncertain data.

    Generated by LLM based on entropy metrics and column context.
    """

    dimension: str  # e.g., "semantic.units", "value.nulls"
    assumption_text: str  # Human-readable assumption
    confidence: str  # "high", "medium", "low"
    impact: str  # What could go wrong if assumption is incorrect
    basis: str = "inferred"  # "inferred", "default", "user_specified"


@dataclass
class ResolutionAction:
    """A suggested action to reduce entropy.

    Generated by LLM with contextual descriptions.
    """

    action: str  # e.g., "document_unit", "document_null_semantics"
    description: str  # Human-readable description
    priority: str  # "high", "medium", "low"
    effort: str  # "low", "medium", "high"
    expected_impact: str  # What dimensions this will improve
    parameters: dict[str, Any] = field(default_factory=dict)


@dataclass
class EntropyInterpretation:
    """Complete interpretation of a column's entropy profile.

    Contains LLM-generated assumptions, resolution actions, and explanation.
    """

    column_name: str | None  # None for table-level interpretations
    table_name: str

    # LLM-generated content
    assumptions: list[Assumption]
    resolution_actions: list[ResolutionAction]
    explanation: str  # Human-readable summary

    # Original metrics for reference
    composite_score: float
    readiness: str

    # Metadata
    model_used: str | None = None

    def to_dashboard_dict(self) -> dict[str, Any]:
        """Convert interpretation to dashboard-friendly dictionary.

        Returns a clean structure suitable for JSON serialization and UI display.
        """
        return {
            "column_key": f"{self.table_name}.{self.column_name}"
            if self.column_name
            else self.table_name,
            "table_name": self.table_name,
            "column_name": self.column_name,
            "explanation": self.explanation,
            "composite_score": round(self.composite_score, 2),
            "readiness": self.readiness,
            "assumptions": [
                {
                    "dimension": a.dimension,
                    "text": a.assumption_text,
                    "confidence": a.confidence,
                    "impact": a.impact,
                }
                for a in self.assumptions
            ],
            "resolution_actions": [
                {
                    "action": r.action,
                    "description": r.description,
                    "priority": r.priority,
                    "effort": r.effort,
                    "parameters": r.parameters,
                }
                for r in self.resolution_actions
            ],
            "metadata": {
                "model_used": self.model_used,
            },
        }


@dataclass
class InterpretationInput:
    """Input data for entropy interpretation.

    Combines entropy profile with raw metrics from detectors.
    """

    table_name: str
    column_name: str
    detected_type: str
    business_description: str | None

    # Entropy profile
    composite_score: float
    readiness: str
    structural_entropy: float
    semantic_entropy: float
    value_entropy: float
    computational_entropy: float

    # Raw metrics from detectors
    raw_metrics: dict[str, Any]

    # Dimension-level scores (e.g., "semantic.dimensional.column_quality": 0.3)
    dimension_scores: dict[str, float]

    # High entropy dimensions
    high_entropy_dimensions: list[str]

    # Compound risks
    compound_risks: list[CompoundRisk]

    # Quality context from ColumnQualityReport (optional, added in interpretation phase)
    quality_grade: str | None = None
    quality_findings: list[str] | None = None

    @classmethod
    def from_summary(
        cls,
        summary: ColumnSummary,
        detected_type: str = "unknown",
        business_description: str | None = None,
        raw_metrics: dict[str, Any] | None = None,
        quality_grade: str | None = None,
        quality_findings: list[str] | None = None,
    ) -> InterpretationInput:
        """Create input from a ColumnSummary.

        Args:
            summary: Column entropy summary
            detected_type: Detected data type
            business_description: Business description if available
            raw_metrics: Raw metrics from detectors
            quality_grade: Quality grade from ColumnQualityReport (A-F)
            quality_findings: Top key findings from quality report

        Returns:
            InterpretationInput ready for LLM
        """
        return cls(
            table_name=summary.table_name,
            column_name=summary.column_name,
            detected_type=detected_type,
            business_description=business_description,
            composite_score=summary.composite_score,
            readiness=summary.readiness,
            structural_entropy=summary.layer_scores.get("structural", 0.0),
            semantic_entropy=summary.layer_scores.get("semantic", 0.0),
            value_entropy=summary.layer_scores.get("value", 0.0),
            computational_entropy=summary.layer_scores.get("computational", 0.0),
            raw_metrics=raw_metrics or {},
            dimension_scores=summary.dimension_scores,
            high_entropy_dimensions=summary.high_entropy_dimensions,
            compound_risks=summary.compound_risks,
            quality_grade=quality_grade,
            quality_findings=quality_findings,
        )


@dataclass
class TableInterpretationInput:
    """Input data for table-level entropy interpretation."""

    table_name: str
    avg_composite_score: float
    max_composite_score: float
    readiness: str
    avg_layer_scores: dict[str, float]
    high_entropy_columns: list[str]
    blocked_columns: list[str]
    compound_risks: list[CompoundRisk]
    column_count: int
    # Summary of per-column dimension scores for pattern detection
    dimension_score_ranges: dict[str, tuple[float, float]]  # dim -> (min, max)

    # Enrichment context (set by interpretation phase, not from_summary)
    dimensional_patterns: list[dict[str, Any]] | None = None
    column_interpretations_summary: list[dict[str, Any]] | None = None
    quality_overview: dict[str, Any] | None = None

    @classmethod
    def from_summary(cls, summary: TableSummary) -> TableInterpretationInput:
        """Create from a TableSummary.

        Args:
            summary: Table entropy summary with column data.

        Returns:
            TableInterpretationInput ready for LLM.
        """
        # Compute dimension score ranges across all columns
        dim_ranges: dict[str, tuple[float, float]] = {}
        for col in summary.columns:
            for dim, score in col.dimension_scores.items():
                if dim in dim_ranges:
                    cur_min, cur_max = dim_ranges[dim]
                    dim_ranges[dim] = (min(cur_min, score), max(cur_max, score))
                else:
                    dim_ranges[dim] = (score, score)

        return cls(
            table_name=summary.table_name,
            avg_composite_score=summary.avg_composite_score,
            max_composite_score=summary.max_composite_score,
            readiness=summary.readiness,
            avg_layer_scores=summary.avg_layer_scores,
            high_entropy_columns=summary.high_entropy_columns,
            blocked_columns=summary.blocked_columns,
            compound_risks=summary.compound_risks,
            column_count=len(summary.columns),
            dimension_score_ranges=dim_ranges,
        )


# =============================================================================
# Pydantic models for LLM tool output
# =============================================================================


class AssumptionOutput(BaseModel):
    """Pydantic model for assumption in LLM tool output."""

    dimension: str = Field(
        description="Entropy dimension this assumption addresses, e.g., 'semantic.units', 'value.nulls'"
    )
    assumption_text: str = Field(description="Human-readable assumption statement")
    confidence: Literal["high", "medium", "low"] = Field(
        description="Confidence level in this assumption"
    )
    impact: str = Field(description="What could go wrong if this assumption is incorrect")


# Valid action prefixes for resolution actions
VALID_ACTION_PREFIXES = ("document_", "investigate_", "transform_", "create_")


class ResolutionActionOutput(BaseModel):
    """Pydantic model for resolution action in LLM tool output."""

    action: str = Field(
        description="Action identifier. Must start with: document_, investigate_, transform_, or create_"
    )
    description: str = Field(description="Human-readable description of the action")
    priority: Literal["high", "medium", "low"] = Field(description="Priority of this action")
    effort: Literal["low", "medium", "high"] = Field(description="Effort required to implement")
    expected_impact: str = Field(description="What entropy dimensions this will improve")
    parameters: dict[str, str] = Field(
        default_factory=dict,
        description="Actionable parameters (e.g., column_name, threshold, strategy, target_table)",
    )

    @field_validator("action")
    @classmethod
    def validate_action_prefix(cls, v: str) -> str:
        """Validate and normalize action prefix.

        If the action doesn't start with a valid prefix, automatically
        add 'document_' as the default prefix rather than rejecting.
        This allows LLM to generate contextual actions like 'account_structure'
        which becomes 'document_account_structure'.
        """
        if not v.startswith(VALID_ACTION_PREFIXES):
            # Auto-prefix with 'document_' as the most common case
            return f"document_{v}"
        return v


class ColumnInterpretationOutput(BaseModel):
    """Pydantic model for a single column interpretation in LLM tool output."""

    assumptions: list[AssumptionOutput] = Field(
        default_factory=list, description="List of assumptions about this column's data"
    )
    resolution_actions: list[ResolutionActionOutput] = Field(
        default_factory=list, description="List of suggested actions to reduce uncertainty"
    )
    explanation: str = Field(
        description="Brief human-readable explanation of the data quality situation"
    )


class EntropyInterpretationOutput(BaseModel):
    """Pydantic model for LLM tool output - batch entropy interpretation.

    Used as a tool definition for structured LLM output via tool use API.
    """

    columns: dict[str, ColumnInterpretationOutput] = Field(
        description="Interpretations keyed by 'table_name.column_name'"
    )


class TableInterpretationLLMOutput(BaseModel):
    """Pydantic model for a single table interpretation in LLM tool output."""

    assumptions: list[AssumptionOutput] = Field(
        default_factory=list, description="List of table-wide assumptions"
    )
    resolution_actions: list[ResolutionActionOutput] = Field(
        default_factory=list, description="List of table-wide actions to reduce uncertainty"
    )
    explanation: str = Field(description="Brief explanation of the table's overall data quality")


class TableEntropyInterpretationOutput(BaseModel):
    """Pydantic model for LLM tool output - batch table interpretation."""

    tables: dict[str, TableInterpretationLLMOutput] = Field(
        description="Interpretations keyed by table_name"
    )


class EntropyInterpreter:
    """LLM-powered entropy interpreter.

    Analyzes entropy metrics and generates contextual assumptions,
    resolution actions, and explanations using structured tool output.

    Note: This class follows the LLMFeature pattern but doesn't inherit
    from it directly to avoid circular imports with entropy module.
    """

    def __init__(
        self,
        config: LLMConfig,
        provider: LLMProvider,
        prompt_renderer: PromptRenderer,
    ) -> None:
        """Initialize entropy interpreter.

        Args:
            config: LLM configuration
            provider: LLM provider instance
            prompt_renderer: Prompt template renderer
        """
        self.config = config
        self.provider = provider
        self.renderer = prompt_renderer

    @staticmethod
    def _validate_column_output(data: dict[str, Any]) -> EntropyInterpretationOutput:
        """Validate column output, auto-wrapping if LLM omitted 'columns' key."""
        try:
            return EntropyInterpretationOutput.model_validate(data)
        except Exception:
            if "columns" not in data:
                return EntropyInterpretationOutput.model_validate({"columns": data})
            raise

    @staticmethod
    def _validate_table_output(data: dict[str, Any]) -> TableEntropyInterpretationOutput:
        """Validate table output, auto-wrapping if LLM omitted 'tables' key."""
        try:
            return TableEntropyInterpretationOutput.model_validate(data)
        except Exception:
            if "tables" not in data:
                return TableEntropyInterpretationOutput.model_validate({"tables": data})
            raise

    def interpret_batch(
        self,
        session: Session,
        inputs: list[InterpretationInput],
        query: str | None = None,
    ) -> Result[dict[str, EntropyInterpretation]]:
        """Interpret entropy for multiple columns in a single LLM call.

        Makes a single batch LLM call for all columns using tool-based output.
        If a query is provided, the model considers how columns interact in that context.

        Args:
            session: Database session
            inputs: List of InterpretationInput for each column
            query: Optional SQL or natural language query for context

        Returns:
            Result containing dict mapping column keys to interpretations
        """
        from dataraum.llm.providers.base import (
            ConversationRequest,
            Message,
            ToolDefinition,
        )

        if not inputs:
            return Result.fail("No inputs provided for interpretation")

        # Choose feature and prompt based on whether query is provided
        if query is not None:
            feature_config = self.config.features.entropy_query_interpretation
            feature_name = "entropy_query_interpretation"
            prompt_name = "entropy_query_interpretation"
        else:
            feature_config = self.config.features.entropy_interpretation
            feature_name = "entropy_interpretation"
            prompt_name = "entropy_interpretation"

        if not feature_config or not feature_config.enabled:
            return Result.fail(f"{feature_name} is disabled in config")

        # Build columns JSON for prompt
        columns_data = []
        for inp in inputs:
            col_entry: dict[str, Any] = {
                "key": f"{inp.table_name}.{inp.column_name}",
                "table_name": inp.table_name,
                "column_name": inp.column_name,
                "detected_type": inp.detected_type,
                "business_description": inp.business_description or "Not documented",
                "composite_score": round(inp.composite_score, 3),
                "readiness": inp.readiness,
                "structural_entropy": round(inp.structural_entropy, 3),
                "semantic_entropy": round(inp.semantic_entropy, 3),
                "value_entropy": round(inp.value_entropy, 3),
                "computational_entropy": round(inp.computational_entropy, 3),
                "dimension_scores": {k: round(v, 3) for k, v in inp.dimension_scores.items()},
                "high_entropy_dimensions": inp.high_entropy_dimensions,
                "raw_metrics": inp.raw_metrics,
                "compound_risks": [
                    {
                        "dimensions": r.dimensions,
                        "risk_level": r.risk_level,
                        "impact": r.impact,
                    }
                    for r in inp.compound_risks
                ],
            }
            # Add quality context if available
            if inp.quality_grade:
                col_entry["quality_grade"] = inp.quality_grade
            if inp.quality_findings:
                col_entry["quality_findings"] = inp.quality_findings
            columns_data.append(col_entry)

        context: dict[str, str] = {
            "columns_json": json.dumps(columns_data, indent=2),
        }
        if query is not None:
            context["query"] = query

        # Render prompt with system/user split
        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                prompt_name, context
            )
        except Exception as e:
            return Result.fail(f"Failed to render prompt: {e}")

        # Define tool for structured output
        tool = ToolDefinition(
            name="interpret_entropy",
            description="Provide structured interpretation of entropy metrics for the columns",
            input_schema=EntropyInterpretationOutput.model_json_schema(),
        )

        model = self.provider.get_model_for_tier(feature_config.model_tier)

        # Call LLM with tool use
        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "interpret_entropy"},
            max_tokens=self.config.limits.max_output_tokens_per_request,
            temperature=temperature,
        )

        # Retry logic for transient failures
        max_retries = 2
        last_error = None

        for _attempt in range(max_retries + 1):
            result = self.provider.converse(request)
            if not result.success or not result.value:
                last_error = result.error or "LLM call failed"
                continue

            response = result.value

            # Extract tool call result
            if not response.tool_calls:
                # LLM didn't use the tool - try to parse text as fallback
                if response.content:
                    try:
                        response_data = json.loads(response.content)
                        output = self._validate_column_output(response_data)
                        return self._convert_output_to_interpretations(inputs, output, model)
                    except Exception:
                        last_error = f"LLM did not use tool. Response: {response.content[:200]}"
                        continue
                else:
                    last_error = "LLM did not use the interpret_entropy tool"
                    continue

            # Parse tool response using Pydantic model
            tool_call = response.tool_calls[0]
            if tool_call.name != "interpret_entropy":
                last_error = f"Unexpected tool call: {tool_call.name}"
                continue

            try:
                output = self._validate_column_output(tool_call.input)
                return self._convert_output_to_interpretations(inputs, output, model)
            except Exception as e:
                last_error = f"Failed to validate tool response: {e}"
                continue

        # All retries failed
        return Result.fail(last_error or "All retry attempts failed")

    def _convert_output_to_interpretations(
        self,
        inputs: list[InterpretationInput],
        output: EntropyInterpretationOutput,
        model: str,
    ) -> Result[dict[str, EntropyInterpretation]]:
        """Convert Pydantic tool output to EntropyInterpretation dataclasses.

        Args:
            inputs: Original input data for each column
            output: Validated Pydantic output from LLM
            model: Model name used for generation

        Returns:
            Result containing dict mapping column keys to interpretations
        """
        # Build lookup for inputs
        inputs_by_key = {f"{inp.table_name}.{inp.column_name}": inp for inp in inputs}

        interpretations: dict[str, EntropyInterpretation] = {}

        # Track key mismatches for diagnostics
        expected_keys = set(inputs_by_key.keys())
        returned_keys = set(output.columns.keys())
        matched_keys = expected_keys & returned_keys
        unmatched_returned = returned_keys - expected_keys
        missing_keys = expected_keys - returned_keys

        if unmatched_returned:
            logger.warning(
                "interpretation_key_mismatch",
                matched=len(matched_keys),
                expected=len(expected_keys),
                returned=len(returned_keys),
                unmatched_returned_keys=sorted(unmatched_returned),
                missing_expected_keys=sorted(missing_keys),
            )

        if len(matched_keys) < len(expected_keys):
            logger.warning(
                "interpretation_columns_lost",
                matched=len(matched_keys),
                total_expected=len(expected_keys),
                total_returned=len(returned_keys),
            )

        for key, col_output in output.columns.items():
            inp = inputs_by_key.get(key)
            if not inp:
                continue

            # Convert assumptions
            assumptions = [
                Assumption(
                    dimension=a.dimension,
                    assumption_text=a.assumption_text,
                    confidence=a.confidence,
                    impact=a.impact,
                    basis="inferred",
                )
                for a in col_output.assumptions
            ]

            # Convert resolution actions
            resolution_actions = [
                ResolutionAction(
                    action=r.action,
                    description=r.description,
                    priority=r.priority,
                    effort=r.effort,
                    expected_impact=r.expected_impact,
                    parameters=r.parameters,
                )
                for r in col_output.resolution_actions
            ]

            interpretations[key] = EntropyInterpretation(
                column_name=inp.column_name,
                table_name=inp.table_name,
                assumptions=assumptions,
                resolution_actions=resolution_actions,
                explanation=col_output.explanation,
                composite_score=inp.composite_score,
                readiness=inp.readiness,
                model_used=model,
            )

        return Result.ok(interpretations)

    def interpret_tables(
        self,
        session: Session,
        inputs: list[TableInterpretationInput],
    ) -> Result[dict[str, EntropyInterpretation]]:
        """Interpret entropy at the table level.

        Makes a single batch LLM call for all tables using tool-based output.

        Args:
            session: Database session
            inputs: List of TableInterpretationInput for each table

        Returns:
            Result containing dict mapping table_name to interpretations
        """
        from dataraum.llm.providers.base import (
            ConversationRequest,
            Message,
            ToolDefinition,
        )

        if not inputs:
            return Result.fail("No inputs provided for table interpretation")

        feature_config = self.config.features.entropy_interpretation
        if not feature_config or not feature_config.enabled:
            return Result.fail("entropy_interpretation is disabled in config")

        # Build tables JSON for prompt
        tables_data = []
        for inp in inputs:
            table_entry: dict[str, Any] = {
                "table_name": inp.table_name,
                "avg_composite_score": round(inp.avg_composite_score, 3),
                "max_composite_score": round(inp.max_composite_score, 3),
                "readiness": inp.readiness,
                "avg_layer_scores": {k: round(v, 3) for k, v in inp.avg_layer_scores.items()},
                "column_count": inp.column_count,
                "high_entropy_columns": inp.high_entropy_columns,
                "blocked_columns": inp.blocked_columns,
                "dimension_score_ranges": {
                    k: {"min": round(v[0], 3), "max": round(v[1], 3)}
                    for k, v in inp.dimension_score_ranges.items()
                },
                "compound_risks": [
                    {
                        "dimensions": r.dimensions,
                        "risk_level": r.risk_level,
                        "impact": r.impact,
                    }
                    for r in inp.compound_risks
                ],
            }
            # Add enrichment context if available
            if inp.dimensional_patterns:
                table_entry["dimensional_patterns"] = inp.dimensional_patterns
            if inp.column_interpretations_summary:
                table_entry["column_interpretations_summary"] = inp.column_interpretations_summary
            if inp.quality_overview:
                table_entry["quality_overview"] = inp.quality_overview
            tables_data.append(table_entry)

        # Extract resolution guidelines from column prompt for reuse
        resolution_guidelines = ""
        try:
            _, full_system, _ = self.renderer.render_split(
                "entropy_interpretation", {"columns_json": "[]"}
            )
            # Extract resolution_guidelines section if present
            if "<resolution_guidelines>" in full_system:
                start = full_system.index("<resolution_guidelines>")
                end = full_system.index("</resolution_guidelines>") + len(
                    "</resolution_guidelines>"
                )
                resolution_guidelines = full_system[start:end]
        except Exception:
            pass

        context: dict[str, str] = {
            "tables_json": json.dumps(tables_data, indent=2),
            "resolution_guidelines": resolution_guidelines,
        }

        # Render prompt
        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                "entropy_table_interpretation", context
            )
        except Exception as e:
            return Result.fail(f"Failed to render table interpretation prompt: {e}")

        # Define tool for structured output
        tool = ToolDefinition(
            name="interpret_table_entropy",
            description="Provide structured interpretation of entropy metrics for the tables",
            input_schema=TableEntropyInterpretationOutput.model_json_schema(),
        )

        model = self.provider.get_model_for_tier(feature_config.model_tier)

        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "interpret_table_entropy"},
            max_tokens=self.config.limits.max_output_tokens_per_request,
            temperature=temperature,
        )

        # Retry logic
        max_retries = 2
        last_error = None

        for _attempt in range(max_retries + 1):
            result = self.provider.converse(request)
            if not result.success or not result.value:
                last_error = result.error or "LLM call failed"
                continue

            response = result.value

            if not response.tool_calls:
                if response.content:
                    try:
                        response_data = json.loads(response.content)
                        output = self._validate_table_output(response_data)
                        return self._convert_table_output(inputs, output, model)
                    except Exception:
                        last_error = f"LLM did not use tool. Response: {response.content[:200]}"
                        continue
                else:
                    last_error = "LLM did not use the interpret_table_entropy tool"
                    continue

            tool_call = response.tool_calls[0]
            if tool_call.name != "interpret_table_entropy":
                last_error = f"Unexpected tool call: {tool_call.name}"
                continue

            try:
                output = self._validate_table_output(tool_call.input)
                return self._convert_table_output(inputs, output, model)
            except Exception as e:
                last_error = f"Failed to validate tool response: {e}"
                continue

        return Result.fail(last_error or "All retry attempts failed")

    def _convert_table_output(
        self,
        inputs: list[TableInterpretationInput],
        output: TableEntropyInterpretationOutput,
        model: str,
    ) -> Result[dict[str, EntropyInterpretation]]:
        """Convert table LLM output to EntropyInterpretation dataclasses."""
        inputs_by_name = {inp.table_name: inp for inp in inputs}
        interpretations: dict[str, EntropyInterpretation] = {}

        # Track key mismatches
        expected_keys = set(inputs_by_name.keys())
        returned_keys = set(output.tables.keys())
        unmatched = returned_keys - expected_keys
        if unmatched:
            logger.warning(
                "table_interpretation_key_mismatch",
                expected_keys=sorted(expected_keys),
                returned_keys=sorted(returned_keys),
                unmatched=sorted(unmatched),
            )

        for table_name, table_output in output.tables.items():
            inp = inputs_by_name.get(table_name)
            if not inp:
                continue

            assumptions = [
                Assumption(
                    dimension=a.dimension,
                    assumption_text=a.assumption_text,
                    confidence=a.confidence,
                    impact=a.impact,
                    basis="inferred",
                )
                for a in table_output.assumptions
            ]

            resolution_actions = [
                ResolutionAction(
                    action=r.action,
                    description=r.description,
                    priority=r.priority,
                    effort=r.effort,
                    expected_impact=r.expected_impact,
                    parameters=r.parameters,
                )
                for r in table_output.resolution_actions
            ]

            interpretations[table_name] = EntropyInterpretation(
                column_name=None,
                table_name=table_name,
                assumptions=assumptions,
                resolution_actions=resolution_actions,
                explanation=table_output.explanation,
                composite_score=inp.avg_composite_score,
                readiness=inp.readiness,
                model_used=model,
            )

        return Result.ok(interpretations)


__all__ = [
    "Assumption",
    "ResolutionAction",
    "EntropyInterpretation",
    "InterpretationInput",
    "TableInterpretationInput",
    "EntropyInterpreter",
    # Pydantic output models for tool use
    "AssumptionOutput",
    "ResolutionActionOutput",
    "ColumnInterpretationOutput",
    "EntropyInterpretationOutput",
    "TableInterpretationLLMOutput",
    "TableEntropyInterpretationOutput",
]
